-- ===========================================================================================
-- CARAVELO VERSION: STORAGE INTEGRATION WITH S3 & EXTERNAL STAGE
-- ===========================================================================================
-- Reference: https://docs.snowflake.com/en/user-guide/data-load-s3-config-storage-integration
-- Updated for Caravelo: 2 CSVs in csv/ folder, 1 JSON in json/ folder
-- ===========================================================================================

-- =======================================================
-- STEP 1 - Databases, Warehouses, and Schemas
-- =======================================================

CREATE DATABASE IF NOT EXISTS CARAVELO_DB;

CREATE SCHEMA IF NOT EXISTS CARAVELO_DB.RAW;       
CREATE SCHEMA IF NOT EXISTS CARAVELO_DB.STAGING;   
CREATE SCHEMA IF NOT EXISTS CARAVELO_DB.ANALYTICS;

USE DATABASE CARAVELO_DB;

-- =======================================================
-- STEP 2 - Roles
-- =======================================================

CREATE ROLE IF NOT EXISTS INGEST_TRANSFORM_ROLE;
CREATE ROLE IF NOT EXISTS ANALYST_ROLE;

-- =======================================================
-- STEP 3 - Grant Privileges
-- =======================================================

-- Engineer role:
GRANT USAGE ON DATABASE CARAVELO_DB TO ROLE INGEST_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA CARAVELO_DB.RAW TO ROLE INGEST_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA CARAVELO_DB.STAGING TO ROLE INGEST_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA CARAVELO_DB.ANALYTICS TO ROLE INGEST_TRANSFORM_ROLE;

GRANT CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA CARAVELO_DB.RAW TO ROLE INGEST_TRANSFORM_ROLE;

GRANT CREATE TABLE, CREATE VIEW 
  ON SCHEMA CARAVELO_DB.STAGING TO ROLE INGEST_TRANSFORM_ROLE;

GRANT CREATE TABLE, CREATE VIEW 
  ON SCHEMA CARAVELO_DB.ANALYTICS TO ROLE INGEST_TRANSFORM_ROLE;

GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE INGEST_TRANSFORM_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA CARAVELO_DB.RAW TO ROLE INGEST_TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CARAVELO_DB.STAGING TO ROLE INGEST_TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CARAVELO_DB.ANALYTICS TO ROLE INGEST_TRANSFORM_ROLE;

-- Analyst role: read-only
GRANT USAGE ON DATABASE CARAVELO_DB TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA CARAVELO_DB.STAGING TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA CARAVELO_DB.ANALYTICS TO ROLE ANALYST_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA CARAVELO_DB.STAGING TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA CARAVELO_DB.ANALYTICS TO ROLE ANALYST_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA CARAVELO_DB.STAGING TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CARAVELO_DB.ANALYTICS TO ROLE ANALYST_ROLE;

-- =======================================================
-- CRITICAL: Transfer ownership of RAW schema to role
-- =======================================================
-- This is essential for dbt run-operation stage_external_sources to work
-- The role needs ownership to create external tables in the schema
GRANT OWNERSHIP ON SCHEMA CARAVELO_DB.RAW TO ROLE INGEST_TRANSFORM_ROLE REVOKE CURRENT GRANTS;

-- =======================================================
-- STEP 4 - Storage Integration with S3
-- =======================================================

CREATE STORAGE INTEGRATION IF NOT EXISTS CARAVELO_S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::286218346471:role/caravelo-role-trust'
  STORAGE_ALLOWED_LOCATIONS = (
    's3://caravelo-data-source/csv/',
    's3://caravelo-data-source/json/'
  );

GRANT USAGE ON INTEGRATION CARAVELO_S3_INTEGRATION TO ROLE INGEST_TRANSFORM_ROLE;

DESC INTEGRATION CARAVELO_S3_INTEGRATION;

-- =======================================================
-- STEP 5 - File Formats
-- =======================================================

CREATE FILE FORMAT IF NOT EXISTS CARAVELO_DB.RAW.CSV_FORMAT
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1;

CREATE FILE FORMAT IF NOT EXISTS CARAVELO_DB.RAW.JSON_FORMAT
  TYPE = JSON;

GRANT USAGE ON FILE FORMAT CARAVELO_DB.RAW.CSV_FORMAT TO ROLE INGEST_TRANSFORM_ROLE;
GRANT USAGE ON FILE FORMAT CARAVELO_DB.RAW.JSON_FORMAT TO ROLE INGEST_TRANSFORM_ROLE;

-- =======================================================
-- STEP 6 - External Stages
-- =======================================================

CREATE STAGE IF NOT EXISTS CARAVELO_DB.RAW.CSV_STAGE
  STORAGE_INTEGRATION = CARAVELO_S3_INTEGRATION
  URL = 's3://caravelo-data-source/csv/'
  FILE_FORMAT = CARAVELO_DB.RAW.CSV_FORMAT;

CREATE STAGE IF NOT EXISTS CARAVELO_DB.RAW.JSON_STAGE
  STORAGE_INTEGRATION = CARAVELO_S3_INTEGRATION
  URL = 's3://caravelo-data-source/json/'
  FILE_FORMAT = CARAVELO_DB.RAW.JSON_FORMAT;

GRANT USAGE ON STAGE CARAVELO_DB.RAW.CSV_STAGE TO ROLE INGEST_TRANSFORM_ROLE;
GRANT USAGE ON STAGE CARAVELO_DB.RAW.JSON_STAGE TO ROLE INGEST_TRANSFORM_ROLE;

LIST @CARAVELO_DB.RAW.CSV_STAGE;
LIST @CARAVELO_DB.RAW.JSON_STAGE;

DESC FILE FORMAT CARAVELO_DB.RAW.CSV_FORMAT;
DESC FILE FORMAT CARAVELO_DB.RAW.JSON_FORMAT;